In [1]:
print("chaliye shuru krte hai")

[1] "chaliye shuru krte hai"


In [4]:
#varriable
a <- 10
b <- 20
c <- a + b
print(c)
#type of variable
print(typeof(a))
print(typeof(b))
print(typeof(c))

[1] 30
[1] "double"
[1] "double"
[1] "double"


In [2]:
#DATATYPES IN R
#1. Numeric 
num <- 5.5
print(num)
#2. Integer
int_num <- 5L
print(int_num)
#3. Character
char <- "Hello"
print(char)
#4. Logical
log_val <- TRUE
print(log_val)
#5. Complex
complex_num <- 2 + 3i

[1] 5.5
[1] 5
[1] "Hello"
[1] TRUE


In [4]:
#converting data types
num_to_char <- as.character(num)
print(num_to_char)
char_to_num <- as.numeric(num_to_char)
print(char_to_num)  
#6. Factor
factor_var <- factor(c("apple", "banana", "apple", "orange"))
print(factor_var)
#7. Date
date_var <- as.Date("2023-10-01")
print(date_var)


[1] "5.5"
[1] 5.5
[1] apple  banana apple  orange
Levels: apple banana orange
[1] "2023-10-01"


In [1]:
#CREATING ARRAY
#CREATE THE SIMPLE ARRAY WITH 2 ROWS AND 3 COLUMNS AND 3 LAYERS 
my_array <- array(1:18, dim = c(2, 3, 3))
print(my_array)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18



In [16]:
# WE CAN NAME THE ROWS AND COLUMNS AND LAYERS OF THE ARRAY
#CREATE AN ARRAY WITH NAMED DIMENSIONS
my_array_named <- array(1:18, dim = c(2, 3, 3), 
 dimnames = list(c("Row1", "Row2"), c("Col1", "Col2", "Col3"), c("Layer1", "Layer2", "Layer3")))
print(my_array_named)
#FILTER THE ARRAY
Filter<-my_array_named[5>2] # Extract the first layer
print(Filter)      

, , Layer1

     Col1 Col2 Col3
Row1    1    3    5
Row2    2    4    6

, , Layer2

     Col1 Col2 Col3
Row1    7    9   11
Row2    8   10   12

, , Layer3

     Col1 Col2 Col3
Row1   13   15   17
Row2   14   16   18

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18


In [12]:
#CREATING ARRAY WITH NAMED DIMENSIONS
ROW_NAMES <- c("Row1", "Row2")
COL_NAMES <- c("Col1", "Col2", "Col3")  
my_array_named <- array(1:18, dim = c(2, 3, 3), 
dimnames = list(ROW_NAMES, COL_NAMES, c("Layer1", "Layer2", "Layer3")))
print(my_array_named)


, , Layer1

     Col1 Col2 Col3
Row1    1    3    5
Row2    2    4    6

, , Layer2

     Col1 Col2 Col3
Row1    7    9   11
Row2    8   10   12

, , Layer3

     Col1 Col2 Col3
Row1   13   15   17
Row2   14   16   18



In [18]:
# WE CAN NAME THE ROWS AND COLUMNS AND LAYERS OF THE ARRAY
#CREATE AN ARRAY WITH NAMED DIMENSIONS
my_array_named <- array(1:18, dim = c(2, 3, 3), 
 dimnames = list(c("Row1", "Row2"), c("Col1", "Col2", "Col3"), c("Layer1", "Layer2", "Layer3")))
print(my_array_named)
#FILTER THE ARRAY (values greater than 10)
Filter <- my_array_named[my_array_named > 10]
print(Filter)

, , Layer1

     Col1 Col2 Col3
Row1    1    3    5
Row2    2    4    6

, , Layer2

     Col1 Col2 Col3
Row1    7    9   11
Row2    8   10   12

, , Layer3

     Col1 Col2 Col3
Row1   13   15   17
Row2   14   16   18

[1] 11 12 13 14 15 16 17 18


In [4]:
#ANOTHER ARRAY WITH CHARACTER DATA
char_array <- array(c("apple", "banana", "cherry", "date", "elderberry", "fig", "grape"), dim = c(2, 3))

In [9]:
# Create a numeric vector
vec <- c(1, 2, 3, 4, 5, 6)

# Use the vector in an array (2 rows, 3 columns)
my_array_from_vec <- array(vec, dim = c(2, 3))
print(my_array_from_vec)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [20]:
#ARRAY BASIC OPERATIONS
# Create a numeric vector
vec <- c(1, 2, 3, 4, 5, 6)
# Use the vector in an array (2 rows, 3 columns)
my_array_from_vec <- array(vec, dim = c(2, 3))
print(my_array_from_vec)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
